version: "2.1"

services:
    app:
        image: nofw/base
        environment:
            APPLICATION_ENV: dev
        volumes:
            - ./:/var/www

    composer:
        image: composer:1.3
        volumes:
            - .:/app

    test:
        image: php:7.1
        command: vendor/bin/phpunit
        environment:
            APPLICATION_ENV: dev
        working_dir: /app
        volumes:
            - ./:/app
